//
//  MockRepoListNetworking.swift
//  GitHubRepos
//
//  Created by Dusan Beljin on 23.3.25..
//

import Foundation

class MockRepoListNetworking: RepoListNetworkingProtocol {
    func fetchRepos(for username: String, completion: @escaping ([Repository]?, ErrorMessage?) -> Void) {

        let data = repoListJson.data(using: .utf8)!
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let decodedResponse = try? decoder.decode([Repository].self, from: data)
        completion(decodedResponse, nil)
    }
    
    let repoListJson = """
    [
      {
        "id": 64778136,
        "node_id": "MDEwOlJlcG9zaXRvcnk2NDc3ODEzNg==",
        "name": "linguist",
        "full_name": "octocat/linguist",
        "private": false,
        "owner": {
          "login": "octocat",
          "id": 583231,
          "node_id": "MDQ6VXNlcjU4MzIzMQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/octocat",
          "html_url": "https://github.com/octocat",
          "followers_url": "https://api.github.com/users/octocat/followers",
          "following_url": "https://api.github.com/users/octocat/following{/other_user}",
          "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
          "organizations_url": "https://api.github.com/users/octocat/orgs",
          "repos_url": "https://api.github.com/users/octocat/repos",
          "events_url": "https://api.github.com/users/octocat/events{/privacy}",
          "received_events_url": "https://api.github.com/users/octocat/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/octocat/linguist",
        "description": "Language Savant. If your repository's language is being reported incorrectly, send us a pull request!",
        "fork": true,
        "url": "https://api.github.com/repos/octocat/linguist",
        "forks_url": "https://api.github.com/repos/octocat/linguist/forks",
        "keys_url": "https://api.github.com/repos/octocat/linguist/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/octocat/linguist/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/octocat/linguist/teams",
        "hooks_url": "https://api.github.com/repos/octocat/linguist/hooks",
        "issue_events_url": "https://api.github.com/repos/octocat/linguist/issues/events{/number}",
        "events_url": "https://api.github.com/repos/octocat/linguist/events",
        "assignees_url": "https://api.github.com/repos/octocat/linguist/assignees{/user}",
        "branches_url": "https://api.github.com/repos/octocat/linguist/branches{/branch}",
        "tags_url": "https://api.github.com/repos/octocat/linguist/tags",
        "blobs_url": "https://api.github.com/repos/octocat/linguist/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/octocat/linguist/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/octocat/linguist/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/octocat/linguist/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/octocat/linguist/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/octocat/linguist/languages",
        "stargazers_url": "https://api.github.com/repos/octocat/linguist/stargazers",
        "contributors_url": "https://api.github.com/repos/octocat/linguist/contributors",
        "subscribers_url": "https://api.github.com/repos/octocat/linguist/subscribers",
        "subscription_url": "https://api.github.com/repos/octocat/linguist/subscription",
        "commits_url": "https://api.github.com/repos/octocat/linguist/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/octocat/linguist/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/octocat/linguist/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/octocat/linguist/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/octocat/linguist/contents/{+path}",
        "compare_url": "https://api.github.com/repos/octocat/linguist/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/octocat/linguist/merges",
        "archive_url": "https://api.github.com/repos/octocat/linguist/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/octocat/linguist/downloads",
        "issues_url": "https://api.github.com/repos/octocat/linguist/issues{/number}",
        "pulls_url": "https://api.github.com/repos/octocat/linguist/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/octocat/linguist/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/octocat/linguist/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/octocat/linguist/labels{/name}",
        "releases_url": "https://api.github.com/repos/octocat/linguist/releases{/id}",
        "deployments_url": "https://api.github.com/repos/octocat/linguist/deployments",
        "created_at": "2016-08-02T17:35:14Z",
        "updated_at": "2025-03-21T01:22:39Z",
        "pushed_at": "2024-08-14T07:35:16Z",
        "git_url": "git://github.com/octocat/linguist.git",
        "ssh_url": "git@github.com:octocat/linguist.git",
        "clone_url": "https://github.com/octocat/linguist.git",
        "svn_url": "https://github.com/octocat/linguist",
        "homepage": "",
        "size": 32899,
        "stargazers_count": 520,
        "watchers_count": 520,
        "language": "Ruby",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 199,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 21,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 199,
        "open_issues": 21,
        "watchers": 520,
        "default_branch": "master"
      },
      {
        "id": 56271164,
        "node_id": "MDEwOlJlcG9zaXRvcnk1NjI3MTE2NA==",
        "name": "test-repo1",
        "full_name": "octocat/test-repo1",
        "private": false,
        "owner": {
          "login": "octocat",
          "id": 583231,
          "node_id": "MDQ6VXNlcjU4MzIzMQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/octocat",
          "html_url": "https://github.com/octocat",
          "followers_url": "https://api.github.com/users/octocat/followers",
          "following_url": "https://api.github.com/users/octocat/following{/other_user}",
          "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
          "organizations_url": "https://api.github.com/users/octocat/orgs",
          "repos_url": "https://api.github.com/users/octocat/repos",
          "events_url": "https://api.github.com/users/octocat/events{/privacy}",
          "received_events_url": "https://api.github.com/users/octocat/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/octocat/test-repo1",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/octocat/test-repo1",
        "forks_url": "https://api.github.com/repos/octocat/test-repo1/forks",
        "keys_url": "https://api.github.com/repos/octocat/test-repo1/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/octocat/test-repo1/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/octocat/test-repo1/teams",
        "hooks_url": "https://api.github.com/repos/octocat/test-repo1/hooks",
        "issue_events_url": "https://api.github.com/repos/octocat/test-repo1/issues/events{/number}",
        "events_url": "https://api.github.com/repos/octocat/test-repo1/events",
        "assignees_url": "https://api.github.com/repos/octocat/test-repo1/assignees{/user}",
        "branches_url": "https://api.github.com/repos/octocat/test-repo1/branches{/branch}",
        "tags_url": "https://api.github.com/repos/octocat/test-repo1/tags",
        "blobs_url": "https://api.github.com/repos/octocat/test-repo1/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/octocat/test-repo1/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/octocat/test-repo1/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/octocat/test-repo1/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/octocat/test-repo1/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/octocat/test-repo1/languages",
        "stargazers_url": "https://api.github.com/repos/octocat/test-repo1/stargazers",
        "contributors_url": "https://api.github.com/repos/octocat/test-repo1/contributors",
        "subscribers_url": "https://api.github.com/repos/octocat/test-repo1/subscribers",
        "subscription_url": "https://api.github.com/repos/octocat/test-repo1/subscription",
        "commits_url": "https://api.github.com/repos/octocat/test-repo1/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/octocat/test-repo1/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/octocat/test-repo1/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/octocat/test-repo1/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/octocat/test-repo1/contents/{+path}",
        "compare_url": "https://api.github.com/repos/octocat/test-repo1/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/octocat/test-repo1/merges",
        "archive_url": "https://api.github.com/repos/octocat/test-repo1/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/octocat/test-repo1/downloads",
        "issues_url": "https://api.github.com/repos/octocat/test-repo1/issues{/number}",
        "pulls_url": "https://api.github.com/repos/octocat/test-repo1/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/octocat/test-repo1/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/octocat/test-repo1/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/octocat/test-repo1/labels{/name}",
        "releases_url": "https://api.github.com/repos/octocat/test-repo1/releases{/id}",
        "deployments_url": "https://api.github.com/repos/octocat/test-repo1/deployments",
        "created_at": "2016-04-14T21:29:25Z",
        "updated_at": "2025-03-17T20:01:29Z",
        "pushed_at": "2024-03-07T11:37:27Z",
        "git_url": "git://github.com/octocat/test-repo1.git",
        "ssh_url": "git@github.com:octocat/test-repo1.git",
        "clone_url": "https://github.com/octocat/test-repo1.git",
        "svn_url": "https://github.com/octocat/test-repo1",
        "homepage": null,
        "size": 1,
        "stargazers_count": 305,
        "watchers_count": 305,
        "language": null,
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 25,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 25,
        "open_issues": 0,
        "watchers": 305,
        "default_branch": "gh-pages"
      }
    ]
    """
}
